[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flet-nfc-plugin"
version = "0.1.0"
description = "Plugin NFC para Flet"
requires-python = ">=3.8"
dependencies = ["flet>=0.27.0"]

[tool.flet.build]
flutter-plugins = ["flet_nfc"]
