[tool.flet.app]
module  = "main"                   # nome do seu main.py sem o “.py”
name    = "Teste NFC"             
package = "com.jh.NFCAppTest"     

[tool.flet.android]
split_per_abi = true               # gera APKs separados
abi_filters   = ["arm64-v8a"]      # apenas ARM64-v8a

[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.NFC"      = true

[tool.flet.android.feature]
"android.hardware.nfc"        = true
