name: flet_client
description: A new Flutter project to host your Flet client.

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flet: any
  nfcflet:
    path: C:\Users\tempe\Desktop\PythonProj\fletnfctest\src\flutter\nfcflet