name: flet_nfc
description: NFC reader control for Flet apps
version: 0.1.0

publish_to: 'none'  # impede publicação acidental no pub.dev

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flet: ^0.28.3
  flutter_nfc_kit: ^3.6.0
  ndef: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  characters: ^1.4.1
  fl_chart: ^1.0.0
  js: ^0.7.2
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  petitparser: ^7.0.0
  sensors_plus: ^6.1.1
  sensors_plus_platform_interface: ^2.0.1
  vector_math: ^2.2.0
  web_socket_channel: ^3.0.3
  window_manager: ^0.5.1
  xml: ^6.6.0
  test_api: ^0.7.7
  vm_service: ^15.0.2

flutter:
  uses-material-design: true
