name: nfcflet
description: Flet Nfcflet control
repository: https://github.com/Jhonataplayyt/nfcflet/src/flutter/nfcflet
version: 0.1.0
homepage: https://github.com/Jhonataplayyt/nfcflet

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.28.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_nfc_kit: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
